#!/bin/python3

import time
import os
import sys

def haider(file, name) :
    file.write("##\n")
    file.write("## Makefile for " + name + " in" + os.getcwd() + "\n")
    file.write("##\n")
    file.write("## Made by " + os.getenv("USER_NICKNAME") +"\n")
    file.write("## Login   <" + os.getenv("USER") + "@epitech.net>\n")
    file.write("##\n")
    tmp = time.asctime(time.localtime(time.time()))
    file.write("## Started on\t" + tmp + " " + os.getenv("USER_NICKNAME") + "\n")
    file.write("## Last update\t" + tmp + " " + os.getenv("USER_NICKNAME")+ "\n")
    file.write("##\n\n")

def     getvar(lib, src):
    LIBOK = 0
    for root, dirs, files in os.walk(".", topdown=False):
        for name in files:
            size = len(name)
            if ('lib' not in os.path.join(root, name)) :
                if (name[size - 2] == '.' and name[size - 1] == 'c') :
                    src.append("\t" + os.path.join(root, name) + " \\\n")
        for name in dirs:
            if ('include'  in name or 'lib/' in os.path.join(root, name)) :
                if ('lib/' in os.path.join(root, name)):
                    LIBOK = 1
                lib.append(name)
    return (LIBOK)


def main(av):
    lib = []
    src = []
    LIBOK = getvar(lib, src)
    FLAG = 0
    if (len(av) < 2 or len(av) > 3):
        print("Usage: ./my_mc \"name exec\" [--flags]")
        exit (1)
    if (len(av) == 3 and av[2] != '--flags'):
        print("Error :  Bad argument " + av[2])
        exit(1)
    if (len(av) == 3):
        FLAG = 1
    file = open("./Makefile", "w")
    haider(file, av[1])
    file.write("NAME =\t" + av[1] + "\n\n")
    file.write("SRC =")
    for name in src:
        file.write(name)
    file.write("\n")
    file.write("OBJ =\t$(SRC:.c=.o)\n\n")
    if (FLAG == 1 or LIBOK == 1 or len(lib) > 0):
        file.write("CFLAGS =")
        if (FLAG == 1):
            file.write("-W\\\n\t-Wall\\\n\t-Werror\\\n")
        if (LIBOK == 1):
            if (FLAG == 1):
                file.write("\t")
            file.write("-L./lib\\\n")
        i = FLAG + LIBOK
        for name in lib:
            if (i != 0):
                file.write("\t")
            if ('include' in name):
                file.write("-I" + os.path.join(".", name) + "\\\n")
            else:
                file.write("-l" + name + "\\\n")
            i += 1
        file.write("\n")
    file.write("all:\t $(NAME)\n\n")
    file.write("$(NAME):$(OBJ)\n\tcc -o $(NAME) $(SRC) $(CFLAGS)\n\n")
    file.write("clean:\n\trm -f $(OBJ)\n\n")
    file.write("fclean:\tclean\n\trm -f $(NAME)\n\n")
    file.write("re:\tfclean all")
    file.close()
    exit(0)

if __name__ == "__main__" :
    main(sys.argv)
